### ISSUE TITLE
Face capture

### ISSUE THREAD

**Issue by felipedeaguiar** [regulaforensics/face-web-components-samples#9]
hello,

I did some tests using the face capture component and in some cases opening it on my cell phone, the component did not load correctly (the mockup did not appear). Could anyone help me with this?

**Comment by felipedeaguiar** [comment]
![image](https://user-images.githubusercontent.com/6431083/220178885-d62093f5-d3cf-4be1-996b-4820625daafe.png)

**Comment by SergeyIlchenko** [comment]
Based on the screenshot, seems like you are using a document reader
This is not a face web component (face-capture)
